coco_contributes_attr_name = ['standing', 'sitting', 'laying', 'walking', 'watching / looking',
                              'eating', 'waiting', 'moving', 'playing', 'sleeping', 'working', 'running', 'hiding',
                              'riding', 'drinking', 'swimming', 'smiling', 'jumping', 'flying', 'traveling', 'enjoying',
                              'thinking', 'loving', 'holding', 'feeding', 'talking', 'floating', 'skiing', 'hunting',
                              'listening', 'hanging', 'grazing', 'skating', 'leaning', 'smelling / sniffing',
                              'socializing', 'stretching', 'driving', 'cooking', 'learning', 'following', 'surfing',
                              'reading', 'climbing', 'bending', 'fishing', 'cuddling', 'smelling', 'panting',
                              'participating', 'racing', 'serving', 'crouching', 'reaching', 'landing', 'hiking ',
                              'waving', 'spectating', 'exercising ', 'carrying', 'snowboarding', 'vacationing ',
                              'shopping', 'catching', 'laughing', 'celebrating', 'angry', 'happy', 'unhappy', 'hungry',
                              'friendly', 'sleepy', 'lazy', 'dry', 'alone / lonely', 'dirty', 'urban', 'busy',
                              'healthy', 'shiny', 'thirsty', 'comfortable / cozy', 'sporty', 'fancy', 'empty', 'furry',
                              'toy', 'messy / cluttered', 'sneaky', 'hairy', 'tasty / delicious', 'bulky', 'frisky',
                              'fluffy', 'fuzzy', 'whole', 'full', 'closed', 'open', 'on ', 'off', 'small', 'large',
                              'long', 'short', 'appetizing', 'filling ', 'curious', 'old', 'young', 'adult', 'calm',
                              'cold', 'cool', 'warm', 'hot', 'clean', 'wet', 'tired', 'playful', 'peaceful', 'useful',
                              'joyful', 'sad', 'scared', 'bored', 'excited', 'anxious', 'annoyed', 'confused', 'modern',
                              'cute / adorable', 'new', 'fake', 'wild', 'natural', 'plastic', 'soft', 'hard',
                              'athletic', 'perched', 'professional', 'spotted', 'male', 'female', 'curled', 'flat',
                              'striped', 'fresh', 'metal / metallic', 'sleek', 'fast', 'round', 'simple ',
                              'unused / inactive', 'safe', 'covered', 'leashed', 'compact', 'adventurous', 'smooth',
                              'rural', 'domestic', 'dull', 'decorative', 'antique / vintage', 'captive', 'strong',
                              'vertical', 'horizontal', 'solid', 'cheap', 'casual', 'expensive', 'functional',
                              'wood / wooden', 'cloth', 'ceramic', 'leather', 'stuffed', 'elegant', 'tame', 'parked',
                              'cooked', 'curved', 'public', 'serious', 'commercial', 'worn', 'portable', 'competitive',
                              'organized', 'dangerous', 'digital', 'electric / electrical', 'plain', 'trendy', 'saucy',
                              'glazed', 'heavy', 'crumpled / wrinkled', 'thin', 'exotic', 'family-friendly']
coco_contributes_attr_type = []
